version: "3.9"

services:
  maptoposter:
    image: nexus.server.cranie.com/maptoposter/maptoposter:latest
    container_name: maptoposter
    restart: unless-stopped
    working_dir: /home/python/app
    command: ["sleep", "infinity"]
